In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 경고 뜨지 않게 설정
import warnings
warnings.filterwarnings('ignore')

# 그래프 설정
sns.set()

# 그래프 기본 설정
plt.rcParams['font.family'] = 'Malgun Gothic'
# plt.rcParams['font.family'] = 'AppleGothic'
plt.rcParams['figure.figsize'] = 12, 6
plt.rcParams['font.size'] = 14
plt.rcParams['axes.unicode_minus'] = False

In [10]:
df = pd.read_parquet('./data/train/3_승인매출정보_train.parquet')
corr_df = pd.read_csv('./corr/3_승인매출정보_상관계수_결측치_제거.csv', encoding='cp949')

In [11]:
corr_df

            Variable  Correlation
0         정상청구원금_B5M    -0.660738
1         정상청구원금_B0M    -0.634571
2         정상청구원금_B2M    -0.628078
3      이용금액_일시불_R12M    -0.595858
4       이용금액_일시불_B0M    -0.575032
..               ...          ...
381    이용금액_당사기타_B0M          NaN
382    이용건수_당사페이_B0M          NaN
383    이용건수_당사기타_B0M          NaN
384  승인거절건수_입력오류_B0M          NaN
385    승인거절건수_기타_B0M          NaN

[386 rows x 2 columns]

In [13]:
filtered_df = corr_df[corr_df["Correlation"].abs() >= 0.4]
filtered_df

           Variable  Correlation
0        정상청구원금_B5M    -0.660738
1        정상청구원금_B0M    -0.634571
2        정상청구원금_B2M    -0.628078
3     이용금액_일시불_R12M    -0.595858
4      이용금액_일시불_B0M    -0.575032
5      이용금액_일시불_R6M    -0.568893
6      이용금액_일시불_R3M    -0.567357
7     이용금액_오프라인_B0M    -0.566186
8        정상입금원금_B5M    -0.551228
9        정상입금원금_B0M    -0.549280
10    이용금액_오프라인_R3M    -0.539827
11    이용금액_오프라인_R6M    -0.538775
12       정상입금원금_B2M    -0.536208
13      _3순위업종_이용금액    -0.504268
14      _2순위업종_이용금액    -0.492209
15    _2순위쇼핑업종_이용금액    -0.487364
16  최대이용금액_일시불_R12M    -0.486145
17     이용건수_신용_R12M    -0.480732
18     이용건수_신판_R12M    -0.476833
19    이용건수_일시불_R12M    -0.472362
20      _1순위업종_이용금액    -0.468099
21    _3순위쇼핑업종_이용금액    -0.464139
22    이용건수_오프라인_B0M    -0.458959
23           이용가맹점수    -0.456553
24      쇼핑_도소매_이용금액    -0.452097
25    이용건수_오프라인_R6M    -0.450232
26    이용건수_오프라인_R3M    -0.449336
27      이용건수_신용_B0M    -0.436677
28      이용건수_신용_R6M    -0.436528
29      이용건수_신용_R3M    -0.433638
30      이용건수_신판_R6M    -0.432737
31      이용건수_신판_B0M    -0.432548
32      이용건수_신판_R3M    -0.429748
33     이용건수_일시불_B0M    -0.429503
34     이용건수_일시불_R6M    -0.429096
35     이용건수_일시불_R3M    -0.426715
36    _1순위교통업종_이용금액    -0.408528
37       연체입금원금_B0M    -0.403665