In [1]:
import pandas as pd
import numpy as np
from dython.nominal import associations
from sklearn.preprocessing import LabelEncoder
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_parquet('1.회원정보_train.parquet')
df1 = pd.read_parquet('4.청구입금정보_train.parquet')

df

,기준년월,ID,남녀구분코드,연령,Segment,회원여부_이용가능,회원여부_이용가능_CA,회원여부_이용가능_카드론,소지여부_신용,소지카드수_유효_신용,...,할인금액_제휴연회비_B0M,청구금액_기본연회비_B0M,청구금액_제휴연회비_B0M,상품관련면제카드수_B0M,임직원면제카드수_B0M,우수회원면제카드수_B0M,기타면제카드수_B0M,카드신청건수,Life_Stage,최종카드발급경과월
0,201807,TRAIN_000000,2,40대,D,1,1,0,1,1,...,0,0,0,0개,0개,0개,0개,0,자녀성장(2),22
1,201807,TRAIN_000001,1,30대,E,1,1,1,1,1,...,0,0,0,0개,0개,0개,0개,0,자녀성장(1),18
2,201807,TRAIN_000002,1,30대,C,1,1,0,1,1,...,0,0,0,0개,0개,0개,0개,0,자녀출산기,20
3,201807,TRAIN_000003,2,40대,D,1,1,0,1,2,...,0,0,0,0개,0개,0개,0개,1,자녀성장(2),17
4,201807,TRAIN_000004,2,40대,E,1,1,1,1,1,...,0,0,0,0개,0개,0개,0개,1,자녀성장(1),15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399995,201812,TRAIN_399995,2,70대이상,E,1,1,1,1,1,...,0,0,0,0개,0개,0개,0개,0,노년생활,39
2399996,201812,TRAIN_399996,2,50대,D,1,1,1,1,1,...,0,0,0,0개,0개,0개,0개,0,자녀성장(2),24
2399997,201812,TRAIN_399997,1,30대,C,1,1,0,1,1,...,0,0,0,0개,0개,0개,0개,0,자녀출산기,18
2399998,201812,TRAIN_399998,1,40대,E,1,1,1,1,1,...,0,0,0,0개,0개,0개,0개,0,자녀성장(1),27
2399999,201812,TRAIN_399999,2,40대,E,1,1,0,1,1,...,0,0,0,0개,0개,0개,0개,0,자녀성장(1),18

In [3]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2400000 entries, 0 to 2399999
Data columns (total 46 columns):
 #   Column            Dtype
---  ------            -----
 0   기준년월              int64
 1   ID                object
 2   대표결제일             int64
 3   대표결제방법코드          object
 4   대표청구지고객주소구분코드     object
 5   대표청구서수령지구분코드      object
 6   청구서수령방법           object
 7   청구서발송여부_B0        int64
 8   청구서발송여부_R3M       int64
 9   청구서발송여부_R6M       int64
 10  청구금액_B0           int64
 11  청구금액_R3M          int64
 12  청구금액_R6M          int64
 13  포인트_마일리지_건별_B0M   int64
 14  포인트_마일리지_건별_R3M   int64
 15  포인트_포인트_건별_B0M    int64
 16  포인트_포인트_건별_R3M    int64
 17  포인트_마일리지_월적립_B0M  int64
 18  포인트_마일리지_월적립_R3M  int64
 19  포인트_포인트_월적립_B0M   int64
 20  포인트_포인트_월적립_R3M   int64
 21  포인트_적립포인트_R12M    int64
 22  포인트_적립포인트_R3M     int64
 23  포인트_이용포인트_R12M    int64
 24  포인트_이용포인트_R3M     int64
 25  포인트_잔여포인트_B0M     int64
 26  마일_적립포인트_R12M     int64
 27  마일_적립포인트_R3M      int64
 28  마일_이용포인트_R12M     int64
 29  마일_이용포인트_R3M      int64
 30  마일_잔여포인트_B0M      int64
 31  할인건수_R3M          object
 32  할인금액_R3M          int64
 33  할인건수_B0M          object
 34  할인금액_B0M          int64
 35  할인금액_청구서_R3M      int64
 36  할인금액_청구서_B0M      int64
 37  상환개월수_결제일_R6M     int64
 38  상환개월수_결제일_R3M     int64
 39  선결제건수_R6M         int64
 40  선결제건수_R3M         int64
 41  연체건수_R6M          int64
 42  연체건수_R3M          int64
 43  혜택수혜금액_R3M        int64
 44  포인트_마일리지_환산_B0M   int64
 45  혜택수혜금액            int64
dtypes: int64(39), object(7)
memory usage: 842.3+ MB

In [4]:
# LabelEncoder 하기

object_col = ['ID','대표결제방법코드','대표청구지고객주소구분코드','대표청구서수령지구분코드','청구서수령방법','할인건수_R3M','할인건수_B0M']

le = LabelEncoder()

for col in object_col:
    df1[col] = le.fit_transform(df1[col].astype(str))

In [5]:
# LabelEncoder 하기
le = LabelEncoder()
df['Segment'] = le.fit_transform(df['Segment'].astype(str))

In [6]:
# 피어슨 상관계수 구하기

segment = df['Segment']

correlations = df1.corrwith(segment, method = 'pearson')

C:\ProgramData\anaconda3\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\ProgramData\anaconda3\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

In [7]:
significant_corr = correlations[correlations.abs() >= 0.1]
print(significant_corr)

청구서발송여부_B0         -0.209534
청구서발송여부_R3M        -0.187036
청구서발송여부_R6M        -0.153697
청구금액_B0            -0.577988
청구금액_R3M           -0.590678
청구금액_R6M           -0.597904
포인트_마일리지_건별_B0M    -0.214917
포인트_마일리지_건별_R3M    -0.216643
포인트_포인트_건별_B0M     -0.144547
포인트_포인트_건별_R3M     -0.146727
포인트_마일리지_월적립_B0M   -0.175594
포인트_마일리지_월적립_R3M   -0.180634
포인트_포인트_월적립_B0M    -0.115605
포인트_포인트_월적립_R3M    -0.125670
포인트_적립포인트_R12M     -0.175362
포인트_적립포인트_R3M      -0.173286
포인트_이용포인트_R12M     -0.143241
포인트_이용포인트_R3M      -0.170152
마일_적립포인트_R12M      -0.213707
마일_적립포인트_R3M       -0.276183
마일_이용포인트_R12M      -0.212008
마일_이용포인트_R3M       -0.213142
마일_잔여포인트_B0M       -0.183546
할인금액_R3M           -0.185652
할인금액_B0M           -0.180181
할인금액_청구서_R3M       -0.202703
할인금액_청구서_B0M       -0.196683
상환개월수_결제일_R6M      -0.149048
상환개월수_결제일_R3M      -0.133415
선결제건수_R6M          -0.158875
선결제건수_R3M          -0.147391
혜택수혜금액_R3M         -0.355754
포인트_마일리지_환산_B0M    -0.281306
혜택수혜금액             -0.350857
dtype: float64

In [32]:
correlations = df1.corrwith(segment, method='pearson')
corr_df = correlations.to_frame()
corr_df

                             0
기준년월              8.217349e-19
ID                1.218077e-03
대표결제일             3.646445e-03
대표결제방법코드                   NaN
대표청구지고객주소구분코드     6.818304e-02
대표청구서수령지구분코드     -1.805543e-02
청구서수령방법          -2.596360e-02
청구서발송여부_B0       -2.095341e-01
청구서발송여부_R3M      -1.870362e-01
청구서발송여부_R6M      -1.536969e-01
청구금액_B0          -5.779884e-01
청구금액_R3M         -5.906781e-01
청구금액_R6M         -5.979035e-01
포인트_마일리지_건별_B0M  -2.149170e-01
포인트_마일리지_건별_R3M  -2.166431e-01
포인트_포인트_건별_B0M   -1.445468e-01
포인트_포인트_건별_R3M   -1.467265e-01
포인트_마일리지_월적립_B0M -1.755938e-01
포인트_마일리지_월적립_R3M -1.806338e-01
포인트_포인트_월적립_B0M  -1.156051e-01
포인트_포인트_월적립_R3M  -1.256698e-01
포인트_적립포인트_R12M   -1.753621e-01
포인트_적립포인트_R3M    -1.732861e-01
포인트_이용포인트_R12M   -1.432407e-01
포인트_이용포인트_R3M    -1.701519e-01
포인트_잔여포인트_B0M     2.584055e-03
마일_적립포인트_R12M    -2.137066e-01
마일_적립포인트_R3M     -2.761832e-01
마일_이용포인트_R12M    -2.120083e-01
마일_이용포인트_R3M     -2.131420e-01
마일_잔여포인트_B0M     -1.835462e-01
할인건수_R3M          5.931681e-02
할인금액_R3M         -1.856518e-01
할인건수_B0M          9.197313e-02
할인금액_B0M         -1.801815e-01
할인금액_청구서_R3M     -2.027028e-01
할인금액_청구서_B0M     -1.966834e-01
상환개월수_결제일_R6M    -1.490485e-01
상환개월수_결제일_R3M    -1.334154e-01
선결제건수_R6M        -1.588749e-01
선결제건수_R3M        -1.473906e-01
연체건수_R6M         -6.050367e-02
연체건수_R3M         -5.481393e-02
혜택수혜금액_R3M       -3.557537e-01
포인트_마일리지_환산_B0M  -2.813062e-01
혜택수혜금액           -3.508569e-01