In [1]:
import pandas as pd
import numpy as np
import os
import re

In [2]:
# 파일 경로 리스트
paths = [
    './undersampled/1_회원정보_balanced.csv',
    './undersampled/2_신용정보_balanced.csv',
    './undersampled/3_승인매출정보_balanced.csv',
    './undersampled/4_청구입금정보_balanced.csv',
    './undersampled/5_잔액정보_balanced.csv',
    './undersampled/6_채널정보_balanced.csv',
    './undersampled/7_마케팅정보_balanced.csv',
    './undersampled/8_성과정보_balanced.csv',
]

In [11]:
df = pd.read_csv('./corr_output/전체_is_C_상관계수_통합.csv')

In [4]:
df

            feature  correlation           source
0              기준년월     0.000296  1_회원정보_balanced
1            남녀구분코드    -0.097586  1_회원정보_balanced
2         회원여부_이용가능     0.129855  1_회원정보_balanced
3      회원여부_이용가능_CA     0.123125  1_회원정보_balanced
4     회원여부_이용가능_카드론    -0.016235  1_회원정보_balanced
..              ...          ...              ...
810      변동률_잔액_B1M     0.005137  8_성과정보_balanced
811  변동률_잔액_일시불_B1M     0.010827  8_성과정보_balanced
812   변동률_잔액_CA_B1M    -0.017839  8_성과정보_balanced
813       혜택수혜율_R3M    -0.141749  8_성과정보_balanced
814       혜택수혜율_B0M    -0.150119  8_성과정보_balanced

[815 rows x 3 columns]

In [4]:
corr_df = df[df['correlation'].abs() >= 0.3]
corr_df

                feature  correlation           source
6           소지카드수_유효_신용     0.403866  1_회원정보_balanced
7         소지카드수_이용가능_신용     0.400320  1_회원정보_balanced
8               입회일자_신용    -0.380032  1_회원정보_balanced
9            입회경과개월수_신용     0.379919  1_회원정보_balanced
22           유효카드수_신용체크     0.393875  1_회원정보_balanced
..                  ...          ...              ...
600        평잔_일시불_해외_6M     0.318694  5_잔액정보_balanced
800  잔액_신판ca평균한도소진율_r6m     0.311938  8_성과정보_balanced
801  잔액_신판ca최대한도소진율_r6m     0.339267  8_성과정보_balanced
802  잔액_신판ca평균한도소진율_r3m     0.317474  8_성과정보_balanced
803  잔액_신판ca최대한도소진율_r3m     0.329521  8_성과정보_balanced

[134 rows x 3 columns]

In [13]:
corr_df = df[df['correlation'].abs() >= 0.4]
corr_df

           feature  correlation           source
6      소지카드수_유효_신용     0.403866  1_회원정보_balanced
7    소지카드수_이용가능_신용     0.400320  1_회원정보_balanced
27    이용가능카드수_신용체크     0.406886  1_회원정보_balanced
28      이용가능카드수_신용     0.403892  1_회원정보_balanced
32      이용카드수_신용체크     0.448962  1_회원정보_balanced
..             ...          ...              ...
528     잔액_일시불_B0M     0.407011  5_잔액정보_balanced
534   월중평잔_일시불_B0M     0.432995  5_잔액정보_balanced
583       월중평잔_일시불     0.432407  5_잔액정보_balanced
589      평잔_일시불_3M     0.426620  5_잔액정보_balanced
599      평잔_일시불_6M     0.442604  5_잔액정보_balanced

[66 rows x 3 columns]

In [14]:
corr_df = df[df['correlation'].abs() >= 0.5]
corr_df

           feature  correlation             source
37   이용금액_R3M_신용체크     0.612636    1_회원정보_balanced
38     이용금액_R3M_신용     0.578470    1_회원정보_balanced
42      _1순위카드이용금액     0.580535    1_회원정보_balanced
118   이용금액_일시불_B0M     0.582582  3_승인매출정보_balanced
136   이용건수_신용_R12M     0.514756  3_승인매출정보_balanced
137   이용건수_신판_R12M     0.508623  3_승인매출정보_balanced
138  이용건수_일시불_R12M     0.503655  3_승인매출정보_balanced
146  이용금액_일시불_R12M     0.538985  3_승인매출정보_balanced
182   이용금액_일시불_R6M     0.592740  3_승인매출정보_balanced
210   이용금액_일시불_R3M     0.583985  3_승인매출정보_balanced
264  _2순위쇼핑업종_이용금액     0.503084  3_승인매출정보_balanced
360  이용금액_오프라인_R6M     0.520333  3_승인매출정보_balanced
364  이용금액_오프라인_R3M     0.527455  3_승인매출정보_balanced
368  이용금액_오프라인_B0M     0.587152  3_승인매출정보_balanced
456     정상청구원금_B0M     0.669647  3_승인매출정보_balanced
458     정상입금원금_B0M     0.526092  3_승인매출정보_balanced
460     정상청구원금_B2M     0.660346  3_승인매출정보_balanced
462     정상입금원금_B2M     0.508536  3_승인매출정보_balanced
464     정상청구원금_B5M     0.669368  3_승인매출정보_balanced
493        청구금액_B0     0.555053  4_청구입금정보_balanced
494       청구금액_R3M     0.573615  4_청구입금정보_balanced
495       청구금액_R6M     0.579846  4_청구입금정보_balanced

In [15]:
from pipeline.preprocessing import merge_segment_df

In [16]:
# from pipeline.preprocessing import merge_segment_df

selected_columns = corr_df['feature'].tolist()

paths = [
    './undersampled/1_회원정보_balanced.csv',
    './undersampled/2_신용정보_balanced.csv',
    './undersampled/3_승인매출정보_balanced.csv',
    './undersampled/4_청구입금정보_balanced.csv',
    './undersampled/5_잔액정보_balanced.csv',
    './undersampled/6_채널정보_balanced.csv',
    './undersampled/7_마케팅정보_balanced.csv',
    './undersampled/8_성과정보_balanced.csv',
]

df = merge_segment_df(selected_columns, paths)

In [17]:
df

,_1순위카드이용금액,이용금액_R3M_신용체크,이용금액_R3M_신용,ID,이용금액_일시불_R3M,이용건수_일시불_R12M,이용건수_신판_R12M,정상입금원금_B0M,이용금액_일시불_B0M,이용금액_일시불_R6M,...,이용건수_신용_R12M,이용금액_오프라인_R6M,_2순위쇼핑업종_이용금액,정상청구원금_B0M,정상청구원금_B5M,정상청구원금_B2M,청구금액_R6M,청구금액_R3M,청구금액_B0,Segment
0,8870,8745,8745,TRAIN_000001,8688,178,178,3365,2779,21660,...,180,22008,502,3384,4195,6024,18311,12473,3428,E
1,6719,7276,7276,TRAIN_000001,8206,177,177,2902,2626,22269,...,179,27766,537,3178,4641,3384,18720,9526,3208,E
2,24493,23988,23988,TRAIN_000002,15694,131,134,12564,5854,35136,...,148,29192,1038,21929,23963,21826,165221,85931,21866,C
3,25118,24421,24421,TRAIN_000002,18936,194,198,12905,6662,38662,...,212,19259,1101,22547,23327,24649,141052,76836,23190,C
4,21833,18657,18657,TRAIN_000002,18402,162,166,17360,5885,35285,...,180,26950,1005,23078,23689,21929,180705,72377,27320,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255175,15126,16916,16916,TRAIN_399997,11208,139,145,5243,4701,25268,...,145,30781,401,6771,12607,9030,43187,21427,6718,C
255176,18378,19942,19942,TRAIN_399997,13549,135,141,6458,4484,22807,...,141,28991,437,6458,10145,4125,43603,18799,8168,C
255177,19248,19956,19956,TRAIN_399997,13544,156,162,6106,4358,21273,...,162,25291,418,6862,9283,6771,38029,22451,7564,C
255178,20206,22498,22498,TRAIN_399997,13364,121,126,4878,4521,24573,...,126,26113,494,6603,8210,6458,46139,24711,8978,C
255179,17171,23187,23187,TRAIN_399997,13424,165,170,5346,4545,26974,...,170,32036,400,7049,4125,6862,41073,22274,5731,C

In [18]:
from pipeline.vif_tools import stepwise_vif_table
import pandas as pd

# 데이터 불러오기
df = df[df['Segment'] == 'C']

# 수치형 컬럼만 선택 (VIF는 수치형만 계산 가능)
numeric_df = df.select_dtypes(include='number')

# VIF 계단식 테이블 생성 및 저장
vif_df, vif_log_df = stepwise_vif_table(
    df=numeric_df,
    min_cols=5,
    output_path="./result/vif_is_C.csv",
    log_path="./result/vif_is_C_removed_log.csv"
)
# 결과 확인
print(vif_df.head())

VIF 테이블 저장 완료: ./result/vif_is_C.csv
제거 로그 저장 완료: ./result/vif_is_C_removed_log.csv
                       22개          21개        20개        19개        18개  \
Variable
_1순위카드이용금액       15.858858    13.465633  12.689820  12.621608  12.611010
_2순위쇼핑업종_이용금액     3.879283     3.818359   3.524954   3.524653   3.494331
이용건수_신용_R12M   7945.720373  1616.406804   3.742189   3.741851   3.454396
이용건수_신판_R12M   8843.958043          NaN        NaN        NaN        NaN
이용건수_일시불_R12M  1871.365030  1676.925217        NaN        NaN        NaN

                     17개        16개        15개        14개       13개       12개  \
Variable
_1순위카드이용금액     12.610473  11.673814  11.666299  11.179148       NaN       NaN
_2순위쇼핑업종_이용금액   3.494260   3.468524   3.465742   3.379890  3.059047  3.040248
이용건수_신용_R12M    3.451497   3.014704   3.014490   2.833169  2.810457  2.807629
이용건수_신판_R12M         NaN        NaN        NaN        NaN       NaN       NaN
이용건수_일시불_R12M        NaN        NaN        NaN        NaN       NaN       NaN

                    11개       10개        9개        8개        7개        6개  \
Variable
_1순위카드이용금액          NaN       NaN       NaN       NaN       NaN       NaN
_2순위쇼핑업종_이용금액  3.034629  3.030288  3.029064  3.027517  2.955906       NaN
이용건수_신용_R12M   2.797453  2.792818  2.514580  2.499397  2.393061  2.216487
이용건수_신판_R12M        NaN       NaN       NaN       NaN       NaN       NaN
이용건수_일시불_R12M       NaN       NaN       NaN       NaN       NaN       NaN

                     5개
Variable
_1순위카드이용금액          NaN
_2순위쇼핑업종_이용금액       NaN
이용건수_신용_R12M   2.164169
이용건수_신판_R12M        NaN
이용건수_일시불_R12M       NaN

In [20]:
df_vif = pd.read_csv('./result/vif_is_C.csv')

In [29]:
top_5 = df_vif[['Variable', '5개']].dropna()

In [30]:
print(top_5)

         Variable        5개
2    이용건수_신용_R12M  2.164169
6   이용금액_R3M_신용체크  2.535917
8   이용금액_오프라인_R3M  2.128922
15     정상입금원금_B2M  2.062910
19        청구금액_B0  1.723440

In [27]:
df_vif[['Variable', '6개']].dropna()

         Variable        6개
2    이용건수_신용_R12M  2.216487
6   이용금액_R3M_신용체크  2.535918
8   이용금액_오프라인_R3M  2.148315
15     정상입금원금_B2M  2.308766
18     정상청구원금_B5M  2.576530
19        청구금액_B0  2.145516

In [23]:
df_vif[['Variable', '7개']].dropna()

         Variable        7개
1   _2순위쇼핑업종_이용금액  2.955906
2    이용건수_신용_R12M  2.393061
6   이용금액_R3M_신용체크  2.808472
8   이용금액_오프라인_R3M  2.259640
15     정상입금원금_B2M  2.311849
18     정상청구원금_B5M  2.615960
19        청구금액_B0  2.177990