In [1]:
import pandas as pd
import numpy as np
import os
import re

In [2]:
df = pd.read_csv('./corr_output/전체_C_D_상관계수_통합.csv')

In [3]:
df

            feature   correlation  source
0              기준년월  4.738604e-13  1_회원정보
1                ID  3.475859e-03  1_회원정보
2            남녀구분코드  4.225881e-02  1_회원정보
3                연령 -6.561087e-02  1_회원정보
4         회원여부_이용가능 -1.370169e-02  1_회원정보
..              ...           ...     ...
866      변동률_잔액_B1M  8.455810e-05  8_성과정보
867  변동률_잔액_일시불_B1M -9.218451e-03  8_성과정보
868   변동률_잔액_CA_B1M  7.350243e-03  8_성과정보
869       혜택수혜율_R3M  1.690438e-02  8_성과정보
870       혜택수혜율_B0M  2.102916e-02  8_성과정보

[871 rows x 3 columns]

In [4]:
df_sorted = df.sort_values(by='correlation', key=abs, ascending=True)

In [5]:
corr = df_sorted[df_sorted['correlation'].abs() >= 0.3]
corr

           feature  correlation    source
138   이용금액_일시불_B0M    -0.303103  3_승인매출정보
498     정상입금원금_B2M    -0.305066  3_승인매출정보
42   이용금액_R3M_신용체크    -0.306900    1_회원정보
502     정상입금원금_B5M    -0.309526  3_승인매출정보
494     정상입금원금_B0M    -0.314765  3_승인매출정보
47      _1순위카드이용금액    -0.318514    1_회원정보
166  이용금액_일시불_R12M    -0.326401  3_승인매출정보
535        청구금액_B0    -0.345636  4_청구입금정보
536       청구금액_R3M    -0.359025  4_청구입금정보
537       청구금액_R6M    -0.360853  4_청구입금정보
496     정상청구원금_B2M    -0.416269  3_승인매출정보
492     정상청구원금_B0M    -0.423459  3_승인매출정보
500     정상청구원금_B5M    -0.438868  3_승인매출정보

In [6]:
corr = df_sorted[df_sorted['correlation'].abs() >= 0.2]
corr

             feature  correlation    source
628         월중평잔_일시불    -0.202417    5_잔액정보
579     월중평잔_일시불_B0M    -0.206489    5_잔액정보
291    _3순위쇼핑업종_이용금액    -0.215420  3_승인매출정보
281      _1순위업종_이용금액    -0.222353  3_승인매출정보
503       연체입금원금_B5M    -0.222789  3_승인매출정보
81            CA한도금액    -0.229117    2_신용정보
404    이용금액_오프라인_B0M    -0.231439  3_승인매출정보
80          카드이용한도금액    -0.236256    2_신용정보
499       연체입금원금_B2M    -0.236261  3_승인매출정보
283      _2순위업종_이용금액    -0.236964  3_승인매출정보
107     카드이용한도금액_B2M    -0.238099    2_신용정보
106     카드이용한도금액_B1M    -0.238996    2_신용정보
289    _2순위쇼핑업종_이용금액    -0.244394  3_승인매출정보
285      _3순위업종_이용금액    -0.244505  3_승인매출정보
400    이용금액_오프라인_R3M    -0.246311  3_승인매출정보
495       연체입금원금_B0M    -0.256541  3_승인매출정보
250      쇼핑_도소매_이용금액    -0.263525  3_승인매출정보
396    이용금액_오프라인_R6M    -0.277599  3_승인매출정보
174  최대이용금액_일시불_R12M    -0.286579  3_승인매출정보
43       이용금액_R3M_신용    -0.288171    1_회원정보
202     이용금액_일시불_R6M    -0.293897  3_승인매출정보
230     이용금액_일시불_R3M    -0.294194  3_승인매출정보
138     이용금액_일시불_B0M    -0.303103  3_승인매출정보
498       정상입금원금_B2M    -0.305066  3_승인매출정보
42     이용금액_R3M_신용체크    -0.306900    1_회원정보
502       정상입금원금_B5M    -0.309526  3_승인매출정보
494       정상입금원금_B0M    -0.314765  3_승인매출정보
47        _1순위카드이용금액    -0.318514    1_회원정보
166    이용금액_일시불_R12M    -0.326401  3_승인매출정보
535          청구금액_B0    -0.345636  4_청구입금정보
536         청구금액_R3M    -0.359025  4_청구입금정보
537         청구금액_R6M    -0.360853  4_청구입금정보
496       정상청구원금_B2M    -0.416269  3_승인매출정보
492       정상청구원금_B0M    -0.423459  3_승인매출정보
500       정상청구원금_B5M    -0.438868  3_승인매출정보