In [2]:
import pandas as pd
import numpy as np
import os
import re

In [2]:
# 파일 경로 리스트
paths = [
    './data/train/1_회원정보_train.parquet',
    './data/train/2_신용정보_train.parquet',
    './data/train/3_승인매출정보_train.parquet',
    './data/train/4_청구입금정보_train.parquet',
    './data/train/5_잔액정보_train.parquet',
    './data/train/6_채널정보_train.parquet',
    './data/train/7_마케팅정보_train.parquet',
    './data/train/8_성과정보_train.parquet',
]

In [15]:
df = pd.read_csv('./corr_output/D_Other/전체_is_D_상관계수_통합.csv')

In [4]:
df

            feature   correlation        source
0              기준년월 -3.742538e-14  1_회원정보_train
1                ID  6.018434e-03  1_회원정보_train
2            남녀구분코드  1.400640e-02  1_회원정보_train
3                연령 -3.598251e-02  1_회원정보_train
4           Segment  9.841903e-01  1_회원정보_train
..              ...           ...           ...
867      변동률_잔액_B1M  1.711321e-02  8_성과정보_train
868  변동률_잔액_일시불_B1M  4.034841e-03  8_성과정보_train
869   변동률_잔액_CA_B1M  6.253987e-03  8_성과정보_train
870       혜택수혜율_R3M -4.328916e-04  8_성과정보_train
871       혜택수혜율_B0M  3.236856e-03  8_성과정보_train

[872 rows x 3 columns]

In [4]:
corr_df = df[df['correlation'].abs() >= 0.1]
corr_df

                feature  correlation  abs_correlation                 source
0            _1순위카드이용금액    -0.323876         0.323876  corr_1_회원정보_train.csv
1         이용금액_R3M_신용체크    -0.310861         0.310861  corr_1_회원정보_train.csv
2           이용금액_R3M_신용    -0.292630         0.292630  corr_1_회원정보_train.csv
3               입회일자_신용     0.201337         0.201337  corr_1_회원정보_train.csv
4            입회경과개월수_신용    -0.201287         0.201287  corr_1_회원정보_train.csv
..                  ...          ...              ...                    ...
157           잔액_할부_B1M    -0.118457         0.118457  corr_5_잔액정보_train.csv
158             월중평잔_할부    -0.118397         0.118397  corr_5_잔액정보_train.csv
159           잔액_할부_B2M    -0.115309         0.115309  corr_5_잔액정보_train.csv
160  잔액_신판ca최대한도소진율_r6m    -0.101913         0.101913  corr_8_성과정보_train.csv
161  잔액_신판ca최대한도소진율_r3m    -0.100388         0.100388  corr_8_성과정보_train.csv

[162 rows x 4 columns]

In [20]:
corr_df = df[df['correlation'].abs() >= 0.25]
corr_df

             feature  correlation  abs_correlation                   source
0         _1순위카드이용금액    -0.323876         0.323876    corr_1_회원정보_train.csv
1      이용금액_R3M_신용체크    -0.310861         0.310861    corr_1_회원정보_train.csv
2        이용금액_R3M_신용    -0.292630         0.292630    corr_1_회원정보_train.csv
23        정상청구원금_B5M    -0.442586         0.442586  corr_3_승인매출정보_train.csv
24        정상청구원금_B0M    -0.428085         0.428085  corr_3_승인매출정보_train.csv
25        정상청구원금_B2M    -0.420720         0.420720  corr_3_승인매출정보_train.csv
26     이용금액_일시불_R12M    -0.331025         0.331025  corr_3_승인매출정보_train.csv
27        정상입금원금_B0M    -0.320133         0.320133  corr_3_승인매출정보_train.csv
28        정상입금원금_B5M    -0.315043         0.315043  corr_3_승인매출정보_train.csv
29        정상입금원금_B2M    -0.310509         0.310509  corr_3_승인매출정보_train.csv
30      이용금액_일시불_B0M    -0.307318         0.307318  corr_3_승인매출정보_train.csv
31      이용금액_일시불_R3M    -0.298280         0.298280  corr_3_승인매출정보_train.csv
32      이용금액_일시불_R6M    -0.297900         0.297900  corr_3_승인매출정보_train.csv
33   최대이용금액_일시불_R12M    -0.290203         0.290203  corr_3_승인매출정보_train.csv
34     이용금액_오프라인_R6M    -0.282652         0.282652  corr_3_승인매출정보_train.csv
35       쇼핑_도소매_이용금액    -0.268614         0.268614  corr_3_승인매출정보_train.csv
36        연체입금원금_B0M    -0.256126         0.256126  corr_3_승인매출정보_train.csv
37     이용금액_오프라인_R3M    -0.251152         0.251152  corr_3_승인매출정보_train.csv
118         청구금액_R6M    -0.366004         0.366004  corr_4_청구입금정보_train.csv
119         청구금액_R3M    -0.364107         0.364107  corr_4_청구입금정보_train.csv
120          청구금액_B0    -0.350537         0.350537  corr_4_청구입금정보_train.csv

In [21]:
from pipeline.preprocessing import merge_segment_df

In [22]:
# from pipeline.preprocessing import merge_segment_df

selected_columns = corr_df['feature'].tolist()

paths = [
    './data/train/1_회원정보_train.parquet',
    './data/train/2_신용정보_train.parquet',
    './data/train/3_승인매출정보_train.parquet',
    './data/train/4_청구입금정보_train.parquet',
    './data/train/5_잔액정보_train.parquet',
    './data/train/6_채널정보_train.parquet',
    './data/train/7_마케팅정보_train.parquet',
    './data/train/8_성과정보_train.parquet',
]


df = merge_segment_df(selected_columns, paths)

In [23]:
df

,ID,이용금액_R3M_신용체크,_1순위카드이용금액,이용금액_R3M_신용,이용금액_일시불_R3M,정상청구원금_B5M,정상청구원금_B0M,이용금액_일시불_R12M,연체입금원금_B0M,정상청구원금_B2M,...,이용금액_오프라인_R3M,이용금액_일시불_B0M,정상입금원금_B2M,쇼핑_도소매_이용금액,최대이용금액_일시불_R12M,이용금액_일시불_R6M,청구금액_R6M,청구금액_R3M,청구금액_B0,Segment
0,TRAIN_000000,196,3681,196,2877,14958,14440,20667,8104,16524,...,4131,1995,16125,0,4906,8380,88693,46588,12226,D
1,TRAIN_000000,-1190,2529,-1190,1250,15593,15008,22754,7322,15712,...,4852,905,15592,0,5350,7041,119419,53336,15756,D
2,TRAIN_000000,868,3948,868,4002,16954,15536,24100,7422,14440,...,11853,1102,6335,0,6009,8282,132269,43715,15732,D
3,TRAIN_000000,-367,3157,-367,3045,16220,15251,23647,7958,15008,...,11715,1037,7685,0,5901,5922,92304,45716,14227,D
4,TRAIN_000000,-478,3048,-478,3203,16718,15028,24417,7864,15536,...,11751,1063,8113,0,6257,4454,97254,43918,13958,D
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399995,TRAIN_399999,17914,7883,17914,3847,6125,3682,19785,323,6112,...,7257,3399,4608,0,5760,14172,28912,16399,3282,E
2399996,TRAIN_399999,23693,11358,23693,9552,7444,4708,17867,640,4514,...,4537,2738,3647,0,6233,11563,42577,10244,4265,E
2399997,TRAIN_399999,17381,8823,17381,9338,6640,5357,18877,2184,3682,...,0,3200,3358,0,6091,16195,23976,11651,4103,E
2399998,TRAIN_399999,20773,8078,20773,9379,7271,4327,18248,1796,4708,...,0,3439,4067,0,4624,13226,26946,10546,2177,E
2399999,TRAIN_399999,21463,6984,21463,9334,4514,3129,12962,467,5357,...,0,2693,3173,0,4593,18887,19948,9704,3422,E

In [24]:
from pipeline.vif_tools import stepwise_vif_table

# 1. Segment가 A/B/C/D만 대상
abcd_df = df[df['Segment'].isin(['A', 'B', 'C', 'D'])].copy()

# 2. is_D 생성 (D: 1, A/B/C: 0)
abcd_df['is_D'] = (abcd_df['Segment'] == 'D').astype(int)

# 삭제 가능한 컬럼만 추림
drop_cols = [col for col in ['ID', '기준년월', 'Segment'] if col in abcd_df.columns]
vif_df = abcd_df.drop(columns=drop_cols)

# 4. 수치형 컬럼만 추출
numeric_df = vif_df.select_dtypes(include='number')

# 5. VIF 계산
vif_table, vif_log = stepwise_vif_table(
    df=numeric_df,
    min_cols=5,
    output_path="./result/vif_d_vs_others.csv",
    log_path="./result/vif_d_vs_others_removed_log.csv"
)

VIF 테이블 저장 완료: ./result/vif_d_vs_others.csv
제거 로그 저장 완료: ./result/vif_d_vs_others_removed_log.csv

In [25]:
df_vif = pd.read_csv('./result/vif_d_vs_others.csv')

In [26]:
top_5 = df_vif[['Variable', '5개']].dropna()

In [27]:
top_5

           Variable        5개
1              is_D  1.223128
2       쇼핑_도소매_이용금액  1.569498
3        연체입금원금_B0M  1.122278
18          청구금액_B0  1.606516
21  최대이용금액_일시불_R12M  1.256710

In [28]:
df_vif[['Variable', '6개']].dropna()

           Variable        6개
1              is_D  1.234142
2       쇼핑_도소매_이용금액  1.824570
3        연체입금원금_B0M  1.133032
5     이용금액_R3M_신용체크  1.971561
18          청구금액_B0  1.683722
21  최대이용금액_일시불_R12M  1.442364

In [32]:
df_vif[['Variable', '8개']].dropna()

           Variable        8개
1              is_D  1.257307
2       쇼핑_도소매_이용금액  2.272643
3        연체입금원금_B0M  1.258424
5     이용금액_R3M_신용체크  2.283334
6     이용금액_오프라인_R3M  2.911130
14       정상입금원금_B5M  2.217845
18          청구금액_B0  2.164519
21  최대이용금액_일시불_R12M  1.710798

In [33]:
print(df_vif[['Variable', '8개']].dropna())

           Variable        8개
1              is_D  1.257307
2       쇼핑_도소매_이용금액  2.272643
3        연체입금원금_B0M  1.258424
5     이용금액_R3M_신용체크  2.283334
6     이용금액_오프라인_R3M  2.911130
14       정상입금원금_B5M  2.217845
18          청구금액_B0  2.164519
21  최대이용금액_일시불_R12M  1.710798

In [36]:
vif_columns  = df_vif[['Variable', '8개']].dropna()['Variable'].tolist()
vif_columns

['is_D',
 '쇼핑_도소매_이용금액',
 '연체입금원금_B0M',
 '이용금액_R3M_신용체크',
 '이용금액_오프라인_R3M',
 '정상입금원금_B5M',
 '청구금액_B0',
 '최대이용금액_일시불_R12M']

In [38]:
selected_columns = [col for col in vif_columns if col != 'is_D']
selected_columns

['쇼핑_도소매_이용금액',
 '연체입금원금_B0M',
 '이용금액_R3M_신용체크',
 '이용금액_오프라인_R3M',
 '정상입금원금_B5M',
 '청구금액_B0',
 '최대이용금액_일시불_R12M']

In [39]:
from pipeline.preprocessing import merge_segment_df

paths = [
    './data/train/1_회원정보_train.parquet',
    './data/train/2_신용정보_train.parquet',
    './data/train/3_승인매출정보_train.parquet',
    './data/train/4_청구입금정보_train.parquet',
    './data/train/5_잔액정보_train.parquet',
    './data/train/6_채널정보_train.parquet',
    './data/train/7_마케팅정보_train.parquet',
    './data/train/8_성과정보_train.parquet'
]

# 함수 실행
merged_df = merge_segment_df(selected_columns, paths)

# 결과 저장
merged_df.to_csv('./result/D_Other_VIF_col_7_with_segment.csv', encoding='utf-8-sig', index=False)

In [40]:
merged_df

,이용금액_R3M_신용체크,ID,연체입금원금_B0M,정상입금원금_B5M,이용금액_오프라인_R3M,쇼핑_도소매_이용금액,최대이용금액_일시불_R12M,청구금액_B0,Segment
0,196,TRAIN_000000,8104,9205,4131,0,4906,12226,D
1,-1190,TRAIN_000000,7322,11161,4852,0,5350,15756,D
2,868,TRAIN_000000,7422,16705,11853,0,6009,15732,D
3,-367,TRAIN_000000,7958,15950,11715,0,5901,14227,D
4,-478,TRAIN_000000,7864,16718,11751,0,6257,13958,D
...,...,...,...,...,...,...,...,...,...
2399995,17914,TRAIN_399999,323,3845,7257,0,5760,3282,E
2399996,23693,TRAIN_399999,640,5697,4537,0,6233,4265,E
2399997,17381,TRAIN_399999,2184,3507,0,0,6091,4103,E
2399998,20773,TRAIN_399999,1796,3645,0,0,4624,2177,E
2399999,21463,TRAIN_399999,467,3647,0,0,4593,3422,E