In [9]:
import os
import pandas as pd

In [2]:
df = pd.read_csv('./data/test/마케팅정보_test.csv')
df

,기준년월,ID,컨택건수_카드론_TM_B0M,컨택건수_리볼빙_TM_B0M,컨택건수_CA_TM_B0M,컨택건수_이용유도_TM_B0M,컨택건수_신용발급_TM_B0M,컨택건수_부대서비스_TM_B0M,컨택건수_포인트소진_TM_B0M,컨택건수_보험_TM_B0M,...,컨택건수_카드론_당사앱_R6M,컨택건수_CA_당사앱_R6M,컨택건수_리볼빙_당사앱_R6M,컨택건수_이용유도_당사앱_R6M,컨택건수_채권_B0M,컨택건수_FDS_B0M,컨택건수_채권_R6M,컨택건수_FDS_R6M,캠페인접촉건수_R12M,캠페인접촉일수_R12M
0,201807,TEST_00000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1회 이상,1일 이상
1,201807,TEST_00001,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,5회 이상,5일 이상
2,201807,TEST_00002,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,10회 이상,10일 이상
3,201807,TEST_00003,3,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,15회 이상,15일 이상
4,201807,TEST_00004,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1회 이상,1일 이상
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599995,201812,TEST_99995,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1회 이상,1일 이상
599996,201812,TEST_99996,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1회 이상,1일 이상
599997,201812,TEST_99997,0,0,0,3,0,0,0,0,...,0,0,0,0,0,0,0,0,1회 이상,1일 이상
599998,201812,TEST_99998,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,5회 이상,5일 이상
599999,201812,TEST_99999,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1회 이상,1일 이상

In [3]:
df.to_csv('./test/마케팅정보_test.csv', index=False, encoding='utf-8-sig')

In [14]:
# 파켓으로 변환
df = pd.read_csv('./data/train/3_승인매출정보_train.csv')
df.to_parquet('3_승인매출정보_train.parquet', index=False)

C:\Users\COTTA\AppData\Local\Temp\ipykernel_28540\3646762002.py:2: DtypeWarning: Columns (183) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('./data/train/3_승인매출정보_train.csv')

In [13]:
df1 = pd.read_parquet('3_승인매출정보_test.parquet')
df1

,기준년월,ID,최종이용일자_기본,최종이용일자_신판,최종이용일자_CA,최종이용일자_카드론,최종이용일자_체크,최종이용일자_일시불,최종이용일자_할부,이용건수_신용_B0M,...,승인거절건수_한도초과_B0M,승인거절건수_BL_B0M,승인거절건수_입력오류_B0M,승인거절건수_기타_B0M,승인거절건수_R3M,승인거절건수_한도초과_R3M,승인거절건수_BL_R3M,승인거절건수_입력오류_R3M,승인거절건수_기타_R3M,이용금액대
0,201807,TEST_00000,20180731,20180731,10101,10101,10101,20180731,20160913,28,...,0,0,0,0,0,0,0,0,0,02.50만원+
1,201807,TEST_00001,20180725,20180725,20170710,20171107,20180731,20180725,20180722,8,...,0,0,0,0,0,0,0,0,0,02.50만원+
2,201807,TEST_00002,20180711,20180711,10101,10101,10101,20180711,20160703,59,...,0,0,0,0,3,3,0,0,0,01.100만원+
3,201807,TEST_00003,20180731,20180731,20150822,20150801,10101,20180731,20160701,37,...,0,0,0,0,0,0,0,0,0,04.10만원+
4,201807,TEST_00004,20180716,20180716,20130917,10101,20180707,20180716,20180708,19,...,0,0,0,0,0,0,0,0,0,03.30만원+
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599995,201812,TEST_99995,20170228,20170228,10101,10101,10101,20170228,10101,-1,...,0,0,0,0,0,0,0,0,0,09.미사용
599996,201812,TEST_99996,20181130,20181130,10101,10101,10101,20181130,10101,0,...,0,0,0,0,0,0,0,0,0,05.10만원-
599997,201812,TEST_99997,10101,10101,10101,10101,10101,10101,10101,3,...,0,0,0,0,0,0,0,0,0,09.미사용
599998,201812,TEST_99998,20181230,20181230,10101,10101,20181225,20181230,20180608,78,...,0,0,0,0,0,0,0,0,0,01.100만원+
599999,201812,TEST_99999,20181205,20181205,10101,10101,10101,20181205,10101,1,...,0,0,0,0,0,0,0,0,0,05.10만원-

In [ ]:
df_list = [df1, df2, df3, df4, df5, df6, df7, df8]

file_names = ['마케팅정보_test.csv', '']