In [1]:
import pandas as pd
import glob
import os

# 1. 병합 대상 경로 설정
csv_dir = "./corr"
csv_files = glob.glob(os.path.join(csv_dir, "*.csv"))

# 2. CSV 파일 읽기 (인코딩 자동 대응)
df_list = []
for file in csv_files:
    try:
        df = pd.read_csv(file, encoding="utf-8")
    except UnicodeDecodeError:
        df = pd.read_csv(file, encoding="cp949")  # 또는 euc-kr
    df_list.append(df)

# 3. 하나로 병합
merged_df = pd.concat(df_list, ignore_index=True)

# 4. 저장 (선택)
merged_df.to_csv("./corr/모든_상관계수_결측치_제거.csv", index=False)

In [4]:
df = merged_df
df

              Variable   Correlation
0        이용금액_R3M_신용체크 -6.228267e-01
1             청구금액_R6M -5.979035e-01
2             청구금액_R3M -5.906781e-01
3          이용금액_R3M_신용 -5.890316e-01
4              청구금액_B0 -5.779884e-01
..                 ...           ...
777  컨택건수_이용유도_인터넷_B0M  2.260987e-03
778    컨택건수_CA_청구서_B0M  1.259665e-03
779     컨택건수_보험_TM_B0M -9.574610e-04
780     컨택건수_CA_TM_R6M -3.480850e-04
781               기준년월  4.040000e-12

[782 rows x 2 columns]

In [2]:
df.to_parquet("./corr/모든_상관계수_결측치_제거.parquet", index=False)

In [3]:
df.isna().sum()

Variable       0
Correlation    0
dtype: int64

In [4]:
df_drop = df.dropna()
df_drop

              Variable   Correlation
0        이용금액_R3M_신용체크 -6.228267e-01
1             청구금액_R6M -5.979035e-01
2             청구금액_R3M -5.906781e-01
3          이용금액_R3M_신용 -5.890316e-01
4              청구금액_B0 -5.779884e-01
..                 ...           ...
710  컨택건수_이용유도_인터넷_B0M  2.260987e-03
711    컨택건수_CA_청구서_B0M  1.259665e-03
712     컨택건수_보험_TM_B0M -9.574610e-04
713     컨택건수_CA_TM_R6M -3.480850e-04
714               기준년월  4.040000e-12

[715 rows x 2 columns]

In [7]:
df_drop.isna().sum()

Variable       0
Correlation    0
dtype: int64

In [ ]:
df_drop.to_csv("./corr/모든_상관계수_결측치_제거.csv", index=False)

In [15]:
df_drop.to_csv("./corr/모든_상관계수_결측치_제거.csv.gz", index=False, compression="gzip")

In [12]:
# 최대 출력 행/열 수 조정
pd.set_option("display.max_rows", None)      # 모든 행 출력
pd.set_option("display.max_columns", None)   # 모든 열 출력

# 열 너비 조정 (너무 긴 열 줄바꿈 방지)
pd.set_option("display.max_colwidth", None)

# 전체 프레임 출력 폭 제한 해제
pd.set_option("display.width", None)

In [6]:
print(df.head(100))

          Variable  Correlation
0    이용금액_R3M_신용체크    -0.622827
1         청구금액_R6M    -0.597904
2         청구금액_R3M    -0.590678
3      이용금액_R3M_신용    -0.589032
4          청구금액_B0    -0.577988
..             ...          ...
95  평잔_RV일시불_해외_6M    -0.121709
96     평잔_RV일시불_6M    -0.120489
97      월중평잔_RV일시불    -0.120210
98       CA이자율_할인전    -0.118189
99  평잔_RV일시불_해외_3M    -0.117664

[100 rows x 2 columns]